bin/bl-apt-update-check: fix syntax for closing file descriptors
Use BASH_SOURCE to find script, falling back to $0
Correctly find script if it is launched by command in $PATH
Add more error checking and comments.

diff --git a/bin/bl-apt-update-check b/bin/bl-apt-update-check
--- a/bin/bl-apt-update-check
+++ b/bin/bl-apt-update-check
@@ -18,6 +18,9 @@
 #
 #    You should have received a copy of the GNU General Public License
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
+#
+#    Reference: https://sourceforge.net/p/yad-dialog/wiki/NotificationIcon/
+#               https://groups.google.com/g/yad-common/c/DT8q1vJ-yOQ?pli=1
 
 HELP="bl-apt-update-check is a script to check if package upgrades are available,
 and if so, display a notification and system tray icon to the user.
@@ -39,8 +42,8 @@ on_exit() {
     echo "quit" >&"$yad_fd" # close yad
     rm -f "${PIPE}"
     rm -rf "${PIPE%/*}"
-    exec "$yad_fd">&-
-    exec "$lockfile_fd">&-
+    exec {yad_fd}>&-
+    exec {lockfile_fd}>&-
     :>"$lockfile" # lockfile holds pid while script is running, otherwise empty
 }
 
@@ -50,10 +53,13 @@ check_pid() {
     local pid=$1
     local script path cmd
     kill -s 0 "$pid" || { echo "${0}: cannot find PID ${pid}" >&2 ; exit 1;}
-    script=$( readlink -e "$0" ) || { echo "${0}: failed to find path to this script" >&2 ; exit 1;}
+    script=$( readlink -e "${BASH_SOURCE:-$0}" ) || { echo "${0}: failed to find path to this script" >&2 ; exit 1;}
     mapfile -d '' -t cmd < "/proc/${pid}/cmdline"
     path=${cmd[-1]} # this script takes no arguments, so it is the last part of the command line
     if [[ $path = /* ]]
+    then
+        path=$(readlink -e "$path")
+    elif path=$(type -p "$path") # resolve a command in $PATH
     then
         path=$(readlink -e "$path")
     else
@@ -65,8 +71,8 @@ check_pid() {
 (( $(id -u) >= 1000 )) || { echo "${0}: this script should only be run by a normal user" >&2 ; exit 1;}
 
 # If there is a previous icon still not closed, kill it (and replace it if still needed).
-lockdir="/run/lock/$(id -u)"
-mkdir -p "$lockdir"
+lockdir="/run/lock/$(id -u)" # separate lockdir for each user
+mkdir -p "$lockdir" || { echo "${0}: failed to create lock directory $lockdir" >&2 ; exit 1;}
 lockfile="$lockdir/bl-apt-update-check-lock"
 exec {lockfile_fd}<>"$lockfile" ||  { echo "${0}: failed to set file descriptor '$lockfile_fd' to $lockfile" >&2 ; exit 1;}
 tries=3 # give up if cannot get lock
@@ -87,11 +93,12 @@ printf '%s' "$$" > "$lockfile" # using lockfile to store pid
 trap on_exit EXIT
 
 show-upgrades(){
-    trap on_exit EXIT
-    [[ -p "$PIPE" ]] || { echo "${0}: there is no fifo $PIPE" >&2 ; exit 1;}
-    exec "$yad_fd"<> "$PIPE" ||  { echo "${0}: show-upgrades(): failed to set file descriptor '$yad_fd' to $PIPE" >&2 ; exit 1;}
+#    trap on_exit EXIT
+#    [[ -p "$PIPE" ]] || { echo "${0}: there is no fifo $PIPE" >&2 ; exit 1;}
+#    exec {yad_fd}<>"$PIPE" ||  { echo "${0}: show-upgrades(): failed to set file descriptor '$yad_fd' to $PIPE" >&2 ; exit 1;}
     x-terminal-emulator -T 'Available Package Upgrades' -e sh -c 'printf "%s\n" "Available upgrades:"; apt list --upgradeable; printf "\n%s\n"  "Held packages:"; apt-mark showhold; bash;'
-    exit
+#    exit
+# TODO: close yad icon when terminal window is closed
 }
 
 dir=$(mktemp --tmpdir --directory "${0##*/}".XXXXXXXX) || { echo "${0}: could not make temp dir" >&2 ; exit 1;}
@@ -99,8 +106,9 @@ PIPE="${dir}/yadpipe"
 mkfifo "$PIPE" || { echo "${0}: could not make fifo $PIPE" >&2 ; exit 1;}
 exec {yad_fd}<> "$PIPE" ||  { echo "${0}: failed to set file descriptor '$yad_fd' to $PIPE" >&2 ; exit 1;}
 
-export PIPE
-export -f on_exit
+#export PIPE
+#export yad_fd
+#export -f on_exit
 export -f show-upgrades
 
 num_upgrades=$(( $( apt list --upgradable 2>/dev/null | wc -l ) - $( apt-mark showhold | wc -l ) -1 ))
