bin/bl-apt-update-check: ensure only one instance is running
If a previously triggered icon is still being displayed, kill it and
if upgrades are still available, display a new one.

diff --git a/bin/bl-apt-update-check b/bin/bl-apt-update-check
--- a/bin/bl-apt-update-check
+++ b/bin/bl-apt-update-check
@@ -21,30 +21,51 @@ on_exit() {
     rm -f "${PIPE}"
     rm -rf "${PIPE%/*}"
     exec 3>&-
+    exec 4>&-
+    :>"$lockfile" # lockfile only holds pid while script is running
 }
+
+# If there is a previous icon still not closed, kill and replace it if still needed
+lockfile='/tmp/bl-apt-update-check-lock'
+exec 4<>"$lockfile"
+tries=3 # give up if cannot get lock
+(( i=1 ))
+until flock --verbose -n 4
+do
+    (( i > tries )) && { echo "${0}: failed to kill old process" >&2 ; exit 1;}
+    echo "${0}: another instance is running, now killing it" >&2
+    oldpid=$(<"$lockfile")
+    kill "$oldpid"
+    tail -f /dev/null --pid="$oldpid" # https://forums.bunsenlabs.org/viewtopic.php?pid=114592#p114592
+    (( i++ )) # one repetition should be enough in fact
+done
+
+printf '%s' "$$" > "$lockfile" # using lockfile to store pid
+
 trap on_exit EXIT
 
-if [[ $1 = '--show-upgrades' ]]
-then
-    PIPE="$2"
+show-upgrades(){
+    trap on_exit EXIT
     [[ -p "$PIPE" ]] || { echo "${0}: there is no fifo $PIPE" >&2 ; exit 1;}
     exec 3<> "$PIPE"
     x-terminal-emulator -T 'Available Package Upgrades' -e sh -c 'printf "%s\n" "Available upgrades:"; apt list --upgradeable; printf "\n%s\n"  "Held packages:"; apt-mark showhold; bash;'
     exit
-fi
+}
 
 dir=$(mktemp --tmpdir --directory "${0##*/}".XXXXXXXX) || { echo "${0}: could not make temp dir" >&2 ; exit 1;}
 PIPE="${dir}/yadpipe"
 mkfifo "$PIPE" || { echo "${0}: could not make fifo $PIPE" >&2 ; exit 1;}
 exec 3<> "$PIPE"
 
+export PIPE
+export -f on_exit
+export -f show-upgrades
+
 num_upgrades=$(( $( apt list --upgradable 2>/dev/null | wc -l ) - $( apt-mark showhold | wc -l ) -1 ))
-script="$( readlink -f "$0" )"
 if (( num_upgrades > 0 )); then
     notify-send  -t 15000 --urgency low "$num_upgrades Upgrades(s) Currently Available"
     yad --notification --listen --image="software-update-available" \
     --text="Package Upgrades - Right-Click For Options" \
-    --menu="Show Available Upgrades!\"$script\" --show-upgrades \"$PIPE\"!applications-other|Quit!quit!application-exit" \
+    --menu="Show Available Upgrades!bash -c show-upgrades!applications-other|Quit!quit!application-exit" \
     --command="notify-send  -t 15000 --urgency low '$num_upgrades Upgrades(s) Currently Available'" <&3
 fi
-
